services:
  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bank
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - appnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    restart: always
    networks:
      - appnet

  springboot-app:
    build:
      context: .
    container_name: springboot-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/bank
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      #SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8080:8080"
    restart: always
    networks:
      - appnet
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
volumes:
  mariadb_data:

networks:
  appnet:
    driver: bridge
